name: build

# Runs the build scripts on PR and when PR is merged to main
on:
  # TODO: Don't need to run this on push to main?
  push:
    branches:
      - main
  pull_request:
    # Only re-run job when certain files have been changed in the PR
    paths:
      - "src/**"
      - "public/**"
      - ".github/workflows/build.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # Run action for [home/clinic] with video [on/off] in [windows/macOS/ubuntu]
    strategy:
      matrix:
        setting: [home, clinic]
        video: [on, off]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        # TODO: Remove video from matrix, add include for the video on home
        exclude:
          # Exclude video on in Ubuntu and macOS
          - os: ubuntu-latest
            setting: clinic
            video: on
          - os: ubuntu-latest
            setting: home
            video: on
          - os: macOS-latest
            setting: clinic
            video: on
          - os: macOS-latest
            setting: home
            video: on
      fail-fast: false # A failed build will not end the other matrix jobs

    steps:
      # Rewrite "git:" repo urls to use "https:" instead, since GitHub Actions blocks port 9418 (as of Jan 2022).
      # TODO: This can be removed?
      - name: Rewrite "git:" repo urls to use "https:" instead.
        run: git config --global url."https://github.com/".insteadOf "git://github.com/"

      # Set up Node
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm

      # Install dependencies and environment
      # TODO: npm ci not npm install
      - name: 📥 Install Dependencies
        # run: |
        #   npm config set "//npm.pkg.github.com/:_authToken" ${{ secrets.GITHUB_TOKEN }}
        #   npm install
        run: npm ci
      - name: 🔃 Load .env file (.env.${{matrix.setting}})
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ./env
          mode: ${{matrix.setting}}
      - name: 🔃 Load .env file (.env.video)
        if: matrix.video=='on'
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ./env
          mode: video

      # Build and test the app
      - name: ⚒ Run Build
        run: npm run build
      - name: 🧪 Run Test
        run: npm test
        env:
          CI: true
